### ISSUE TITLE
jsluice extension dosn't detect $PATH 

### ISSUE THREAD

**Issue by ak1t4** [0x999-x/jsluicepp#3]
i have set correctly jsluice binary in my bash enviroment $PATH

but still getting this error in burp:

Extension loaded
[WARNING] jsluice binary not found, please install it and ensure it is in your $PATH otherwise the extension will not work.

any ideas?

thanks

**Comment by 0x999-x** [comment]
Hi @ak1t4,
could you try running ```which jsluice``` in your terminal and see if it returns the path?
I assume it's happening because the user you're running burp suite from has a different $PATH than the user you installed jsluice on
if all fails you can solve this by using a hardcoded path in the code by modifying the [urls_command](https://github.com/0x999-x/jsluicepp/blob/main/jsluicepp.py#L1331) and [secrets_command](https://github.com/0x999-x/jsluicepp/blob/main/jsluicepp.py#L1357) in the code

**Comment by Teicu** [comment]
I'm experiencing the same issue. After installing it on my Mac, I'm unable to find anything.

<img width="814" alt="Screenshot 2024-02-12 at 08 36 09" src="https://github.com/0x999-x/jsluicepp/assets/1572822/7973b42b-7f83-4951-bd82-ea0cdfb64a67"> 

<img width="1306" alt="Screenshot 2024-02-12 at 08 38 12" src="https://github.com/0x999-x/jsluicepp/assets/1572822/3fd16e6e-3bf6-476c-ad17-0849484e2ad0">

**Comment by Teicu** [comment]
which jsluice
/Users/admin/jsluice

**Comment by Teicu** [comment]
Thank you for your time, I did this, so basically I changed  

on page 1331 to **_urls_command = "jsluice urls /Users/admin/jsluice"_**

on page 1357 with **_secrets_command = "jsluice secrets /Users/admin/jsluice"_** 

is this correct? 
 
unfortunately, it still doesn't work

**Comment by 0x999-x** [comment]
> Thank you for your time, I did this, so basically I changed
> 
> on page 1331 to **_urls_command = "jsluice urls /Users/admin/jsluice"_**
> 
> on page 1357 with **_secrets_command = "jsluice secrets /Users/admin/jsluice"_**
> 
> is this correct?
> 
> unfortunately, it still doesn't work

Modify ```urls_command = "jsluice urls " + file_path``` to ```urls_command = "/Users/admin/jsluice urls " + file_path```
and ```secrets_command = "jsluice secrets " + file_path``` to ```secrets_command = "/Users/admin/jsluice secrets " + file_path```

**Comment by Teicu** [comment]
Hi, I've made the adjustments, but unfortunately, I've encountered an error. This option used to function properly, but now it seems to be non-functional. From what you ca see it's not processing anything anymore. 

<img width="1389" alt="Screenshot 2024-02-12 at 13 45 19" src="https://github.com/0x999-x/jsluicepp/assets/1572822/2f3c1937-9146-4147-87a4-2522450b2350">

**Comment by Teicu** [comment]
do you think the problem might be here? 

which jsluice
/Users/admin/jsluice
➜  ~ jsluice
/Users/admin/jsluice: line 1: syntax error near unexpected token `newline' 

/Users/admin/jsluice: line 1: `!<arch>'

**Comment by 0x999-x** [comment]
> do you think the problem might be here?
> 
> which jsluice /Users/admin/jsluice ➜ ~ jsluice /Users/admin/jsluice: line 1: syntax error near unexpected token `newline'
> 
> /Users/admin/jsluice: line 1: `!'

Yeah that's most likely it, try reinstalling the jsluice binary(```go install github.com/BishopFox/jsluice/cmd/jsluice@latest```), once you got that working everything should be fine

**Comment by Teicu** [comment]
Hi, It works perfectly now, thank you very much for your time! 

Cheers

**Comment by 0x999-x** [comment]
Closing this as completed as a file selector for jsluice's binary was added in bfa1aa7944414f13f8bcf4dfc07de93e9cb0a60f, if you are still encountering this problem please raise a new Issue.

**Comment by Sicks3c** [comment]
Hey I'm facing the same issue too
<img width="913" alt="Screenshot 2024-12-11 at 09 37 29" src="https://github.com/user-attachments/assets/91b29668-2131-4591-a890-badd80be4ee4">

![image](https://github.com/user-attachments/assets/4875ed08-746c-4477-a922-55932caac446)

System Mac M1
