### ISSUE TITLE
windows 

### ISSUE THREAD

**Issue by f00010100** [0x999-x/jsluicepp#7]
has anyone using burp on windows tried this? having permission issues

**Comment by f00010100** [comment]
hey, so i wasn't clear the first time. I'm using windows OS on my PC and have have ubuntu installed through wsl. my jsluice is on installed on the ubuntu but my burp is on windows. i downloaded the jsluicepp.py on my windows OS but I can't access jsluice from the extension tab in burpsuite. what do you suggest @0x999-x ty :)

**Comment by 0x999-x** [comment]
Hey @f00010100 ,

You can't use the linux jsluice binary while having the extension running on windows as it will try to execute the jsluice binary from windows, You can solve this by compiling jsluice on windows and using that, you might have to use a hardcoded path in jsluice++'s code, there's a weird bug I saw happening on windows sometimes where it fails to find the binary using the file selector, haven't had the chance to investigate yet.
if you need help with that feel free to DM [me](https://x.com/_0x999) on X.

**Comment by f00010100** [comment]
hey, so i just installed jsluice directly on windows and selected the path on burp for jsluice++ and it worked. 
p.s CLAUDE IS THE GOAT
